// 인증 TTL (이메일/SMS/아이디찾기 등) - 분 단위로 정의 후 초로 변환
const SECONDS_PER_MINUTE = 60

export const EMAIL_VERIFICATION_TTL_MINUTES = 5
export const EMAIL_VERIFICATION_TTL_SECONDS =
  EMAIL_VERIFICATION_TTL_MINUTES * SECONDS_PER_MINUTE

export const SMS_VERIFICATION_TTL_MINUTES = 10
export const SMS_VERIFICATION_TTL_SECONDS =
  SMS_VERIFICATION_TTL_MINUTES * SECONDS_PER_MINUTE

export const FIND_ID_PASSWORD_TTL_MINUTES = 5
export const FIND_ID_PASSWORD_TTL_SECONDS =
  FIND_ID_PASSWORD_TTL_MINUTES * SECONDS_PER_MINUTE

export const VERIFICATION_TTL_SECONDS = EMAIL_VERIFICATION_TTL_SECONDS
